import 'package:flutter/material.dart';

import '../../app/app_text.dart';
import 'guided_tour.dart';
import 'tour_ledger_example.dart';

/// Anclas del tour: los widgets reales a los que apuntan los pasos.
///
/// Viven en la pantalla principal y se pasan al tour, para que este pueda
/// iluminar los botones de verdad en lugar de dibujar una explicación abstracta.
class ShardPayTourAnchors {
  ShardPayTourAnchors();

  final GlobalKey crearGrupo = GlobalKey(debugLabel: 'tour.crearGrupo');
  final GlobalKey buscar = GlobalKey(debugLabel: 'tour.buscar');
  final GlobalKey entrarPorEnlace = GlobalKey(debugLabel: 'tour.entrarPorEnlace');
  final GlobalKey listaGrupos = GlobalKey(debugLabel: 'tour.listaGrupos');
  final GlobalKey navegacion = GlobalKey(debugLabel: 'tour.navegacion');
}

/// Pestañas de la pantalla principal, en el orden de la barra inferior.
class TourTabs {
  const TourTabs._();

  static const int grupos = 0;
  static const int balanceGlobal = 1;
  static const int estadisticas = 2;
}

/// Lanza el tour de bienvenida de ShardPay.
///
/// [onSelectTab] deja que el tour cambie de pestaña: los pasos de deudas y de
/// estadísticas explican pantallas distintas, y enseñarlas de verdad vale más
/// que describirlas.
///
/// Devuelve `true` si se completó entero.
Future<bool> showShardPayTour(BuildContext context, ShardPayTourAnchors anclas, {required Future<void> Function(int tab) onSelectTab}) {
  return showGuidedTour(context, _pasos(context, anclas, onSelectTab));
}

List<TourStep> _pasos(BuildContext context, ShardPayTourAnchors anclas, Future<void> Function(int tab) onSelectTab) {
  return <TourStep>[
    // 1 ------------------------------------------------------------------
    TourStep(
      icon: Icons.waving_hand_rounded,
      onEnter: () => onSelectTab(TourTabs.grupos),
      title: tr(
        context,
        es: 'Bienvenido a ShardPay',
        en: 'Welcome to ShardPay',
        gl: 'Benvido a ShardPay',
        ca: 'Benvingut a ShardPay',
        eu: 'Ongi etorri ShardPay-ra',
        fr: 'Bienvenue sur ShardPay',
        it: 'Benvenuto su ShardPay',
        pt: 'Bem-vindo ao ShardPay',
        de: 'Willkommen bei ShardPay',
        el: 'Καλώς ήρθες στο ShardPay',
        ru: 'Добро пожаловать в ShardPay',
        ar: 'مرحبا بك في ShardPay',
        zh: '欢迎使用 ShardPay',
        ja: 'ShardPay へようこそ',
      ),
      body: tr(
        context,
        es: 'Voy a acompañarte por un viaje de ejemplo con cuatro amigos: quién paga qué, cómo quedan las deudas y qué cuentan las estadísticas. Un minuto. Puedes saltártelo y volver a verlo desde Ajustes.',
        en: 'I will walk you through an example trip with four friends: who pays what, how the debts end up, and what the stats tell you. One minute. You can skip it and replay it from Settings.',
        gl: 'Vouche acompañar por unha viaxe de exemplo con catro amigos: quen paga que, como quedan as débedas e que contan as estatísticas. Un minuto. Podes saltalo e volver velo desde Axustes.',
        ca: 'T acompanyo per un viatge d exemple amb quatre amics: qui paga què, com queden els deutes i què expliquen les estadístiques. Un minut.',
        eu: 'Lau lagunen adibide-bidaia batean lagunduko dizut: nork zer ordaintzen duen, zorrak nola geratzen diren eta estatistikek zer kontatzen duten. Minutu bat.',
        fr: 'Je vous accompagne dans un voyage d exemple à quatre : qui paie quoi, comment se soldent les dettes et ce que disent les statistiques. Une minute.',
        it: 'Ti accompagno in un viaggio di esempio con quattro amici: chi paga cosa, come restano i debiti e cosa raccontano le statistiche. Un minuto.',
        pt: 'Vou acompanhar-te numa viagem de exemplo com quatro amigos: quem paga o quê, como ficam as dívidas e o que contam as estatísticas. Um minuto.',
        de: 'Ich führe dich durch eine Beispielreise mit vier Freunden: wer was zahlt, wie die Schulden ausgehen und was die Statistiken sagen. Eine Minute.',
        el: 'Θα σε ξεναγήσω σε ένα ταξίδι-παράδειγμα με τέσσερις φίλους: ποιος πληρώνει τι, πώς μένουν τα χρέη και τι λένε τα στατιστικά. Ένα λεπτό.',
        ru: 'Проведу вас по примеру поездки вчетвером: кто что платит, как складываются долги и что показывает статистика. Одна минута.',
        ar: 'سأصحبك في رحلة مثال مع أربعة أصدقاء: من يدفع ماذا، وكيف تنتهي الديون، وماذا تقول الإحصاءات. دقيقة واحدة.',
        zh: '我会用一次四人旅行的例子带你走一遍：谁付了什么、欠款怎么结算、统计说明了什么。一分钟。',
        ja: '4 人旅行の例で案内します。誰が何を払い、貸し借りがどうなり、統計が何を示すか。1 分ほどです。',
      ),
    ),

    // 2 ------------------------------------------------------------------
    TourStep(
      icon: Icons.group_add_rounded,
      targetKey: anclas.crearGrupo,
      radius: 26,
      title: tr(
        context,
        es: 'Todo empieza con un grupo',
        en: 'It all starts with a group',
        gl: 'Todo empeza cun grupo',
        ca: 'Tot comença amb un grup',
        eu: 'Dena talde batekin hasten da',
        fr: 'Tout commence par un groupe',
        it: 'Tutto parte da un gruppo',
        pt: 'Tudo começa com um grupo',
        de: 'Alles beginnt mit einer Gruppe',
        el: 'Όλα ξεκινούν με μια ομάδα',
        ru: 'Всё начинается с группы',
        ar: 'كل شيء يبدأ بمجموعة',
        zh: '一切从一个群组开始',
        ja: 'すべてはグループから',
      ),
      body: tr(
        context,
        es: 'En el ejemplo, Brais crea «Roadtrip Costa» y elige el euro. Se apuntan Noa, Leo y Marta. Puedes añadir gente que todavía no tenga cuenta: aparece por su nombre y se vincula después.',
        en: 'In the example, Brais creates "Roadtrip Costa" and picks the euro. Noa, Leo and Marta join. You can add people without an account: they show up by name and link themselves later.',
        gl: 'No exemplo, Brais crea «Roadtrip Costa» e escolle o euro. Apúntanse Noa, Leo e Marta. Podes engadir xente sen conta: aparece polo seu nome e vincúlase despois.',
        ca: 'A l exemple, en Brais crea «Roadtrip Costa» i tria l euro. S hi apunten la Noa, en Leo i la Marta.',
        eu: 'Adibidean, Braisek «Roadtrip Costa» sortzen du eta euroa aukeratzen. Noa, Leo eta Marta batzen dira.',
        fr: 'Dans l exemple, Brais crée « Roadtrip Costa » et choisit l euro. Noa, Leo et Marta rejoignent.',
        it: 'Nell esempio, Brais crea «Roadtrip Costa» e sceglie l euro. Si uniscono Noa, Leo e Marta.',
        pt: 'No exemplo, o Brais cria «Roadtrip Costa» e escolhe o euro. Juntam-se a Noa, o Leo e a Marta.',
        de: 'Im Beispiel erstellt Brais „Roadtrip Costa" und wählt den Euro. Noa, Leo und Marta treten bei.',
        el: 'Στο παράδειγμα, ο Brais δημιουργεί το «Roadtrip Costa» και διαλέγει το ευρώ. Μπαίνουν η Noa, ο Leo και η Marta.',
        ru: 'В примере Брайс создаёт «Roadtrip Costa» и выбирает евро. Присоединяются Ноа, Лео и Марта.',
        ar: 'في المثال، ينشئ Brais مجموعة «Roadtrip Costa» ويختار اليورو. ينضم إليه Noa وLeo وMarta.',
        zh: '例子里，Brais 创建「Roadtrip Costa」并选择欧元。Noa、Leo 和 Marta 加入。',
        ja: '例では Brais が「Roadtrip Costa」を作り、ユーロを選びます。Noa・Leo・Marta が参加します。',
      ),
    ),

    // 3 ------------------------------------------------------------------
    TourStep(
      icon: Icons.qr_code_scanner_rounded,
      targetKey: anclas.entrarPorEnlace,
      title: tr(
        context,
        es: 'Así entran los demás',
        en: 'This is how the others join',
        gl: 'Así entran os demais',
        ca: 'Així hi entren els altres',
        eu: 'Horrela sartzen dira besteak',
        fr: 'C est ainsi que les autres arrivent',
        it: 'Così entrano gli altri',
        pt: 'É assim que os outros entram',
        de: 'So kommen die anderen dazu',
        el: 'Έτσι μπαίνουν οι υπόλοιποι',
        ru: 'Так подключаются остальные',
        ar: 'هكذا ينضم الآخرون',
        zh: '其他人这样加入',
        ja: '他の人はこう参加します',
      ),
      body: tr(
        context,
        es: 'Brais comparte el enlace del grupo por el chat del viaje. Noa, Leo y Marta lo pulsan y ya están dentro. También vale el código QR si estáis juntos.',
        en: 'Brais shares the group link in the trip chat. Noa, Leo and Marta tap it and they are in. The QR code works too if you are together.',
        gl: 'Brais comparte a ligazón do grupo no chat da viaxe. Noa, Leo e Marta prémena e xa están dentro. Tamén vale o código QR.',
        ca: 'En Brais comparteix l enllaç al xat del viatge. La resta el toquen i ja hi són. També serveix el codi QR.',
        eu: 'Braisek taldearen esteka partekatzen du bidaiaren txatean. Besteek sakatu eta barruan daude. QR kodea ere balio du.',
        fr: 'Brais partage le lien du groupe dans la discussion du voyage. Les autres cliquent et les voilà dedans.',
        it: 'Brais condivide il link del gruppo nella chat del viaggio. Gli altri lo toccano e sono dentro.',
        pt: 'O Brais partilha a ligação do grupo no chat da viagem. Os outros tocam e já estão dentro.',
        de: 'Brais teilt den Gruppenlink im Reise-Chat. Die anderen tippen darauf und sind drin.',
        el: 'Ο Brais μοιράζεται τον σύνδεσμο στη συνομιλία του ταξιδιού. Οι άλλοι τον πατούν και μπαίνουν.',
        ru: 'Брайс отправляет ссылку в чат поездки. Остальные жмут — и они внутри.',
        ar: 'يشارك Brais رابط المجموعة في محادثة الرحلة. يضغط الآخرون فيدخلون.',
        zh: 'Brais 把群组链接发到旅行群里，其他人点一下就进来了。',
        ja: 'Brais が旅行のチャットにグループのリンクを共有。他の人はタップするだけで参加できます。',
      ),
    ),

    // 4 ------------------------------------------------------------------
    TourStep(
      icon: Icons.receipt_long_rounded,
      targetKey: anclas.listaGrupos,
      radius: 24,
      illustration: const TourExpensesExample(),
      title: tr(
        context,
        es: 'Cada uno apunta lo que paga',
        en: 'Everyone logs what they pay',
        gl: 'Cada un apunta o que paga',
        ca: 'Cadascú apunta el que paga',
        eu: 'Bakoitzak ordaintzen duena apuntatzen du',
        fr: 'Chacun note ce qu il paie',
        it: 'Ognuno annota quello che paga',
        pt: 'Cada um regista o que paga',
        de: 'Jeder trägt ein, was er zahlt',
        el: 'Ο καθένας καταγράφει τι πληρώνει',
        ru: 'Каждый вносит то, что заплатил',
        ar: 'كل شخص يسجل ما يدفعه',
        zh: '每个人记录自己付的钱',
        ja: '各自が払った分を記録',
      ),
      body: tr(
        context,
        es: 'Durante el viaje, cada persona apunta sus gastos desde su móvil. El resto los ve al instante. Puedes escribirlos a mano o fotografiar el ticket con «Ticket con cámara» y dejar que la app lea las líneas.',
        en: 'During the trip, each person logs their expenses from their own phone. Everyone else sees them instantly. Type them in, or photograph the receipt with "Receipt with camera" and let the app read the lines.',
        gl: 'Durante a viaxe, cada persoa apunta os seus gastos desde o seu móbil. O resto veos ao instante. Podes escribilos ou fotografar o ticket coa cámara.',
        ca: 'Durant el viatge, cadascú apunta les seves despeses des del seu mòbil. La resta les veu a l instant.',
        eu: 'Bidaian zehar, bakoitzak bere gastuak apuntatzen ditu bere mugikorretik. Besteek berehala ikusten dituzte.',
        fr: 'Pendant le voyage, chacun note ses dépenses depuis son téléphone. Les autres les voient aussitôt.',
        it: 'Durante il viaggio, ognuno annota le sue spese dal proprio telefono. Gli altri le vedono subito.',
        pt: 'Durante a viagem, cada um regista as suas despesas do seu telemóvel. Os outros veem-nas de imediato.',
        de: 'Während der Reise trägt jeder seine Ausgaben vom eigenen Handy ein. Alle anderen sehen sie sofort.',
        el: 'Στη διάρκεια του ταξιδιού, ο καθένας καταγράφει τα έξοδά του από το κινητό του. Οι υπόλοιποι τα βλέπουν αμέσως.',
        ru: 'В поездке каждый вносит свои траты со своего телефона. Остальные видят их сразу.',
        ar: 'خلال الرحلة، يسجل كل شخص مصاريفه من هاتفه. ويراها الباقون فورا.',
        zh: '旅途中每个人用自己的手机记账，其他人立刻就能看到。',
        ja: '旅行中は各自が自分のスマホで支出を記録。ほかの人にはすぐ反映されます。',
      ),
    ),

    // 5 ------------------------------------------------------------------
    TourStep(
      icon: Icons.tune_rounded,
      targetKey: anclas.listaGrupos,
      radius: 24,
      title: tr(
        context,
        es: 'No todo se reparte entre todos',
        en: 'Not everything is split by everyone',
        gl: 'Non todo se reparte entre todos',
        ca: 'No tot es reparteix entre tothom',
        eu: 'Ez da dena guztien artean banatzen',
        fr: 'Tout ne se partage pas à quatre',
        it: 'Non tutto si divide fra tutti',
        pt: 'Nem tudo se divide por todos',
        de: 'Nicht alles teilen sich alle',
        el: 'Δεν μοιράζονται όλα σε όλους',
        ru: 'Не всё делится на всех',
        ar: 'ليس كل شيء يقسم على الجميع',
        zh: '并非所有开销都平摊',
        ja: 'すべてを全員で割るわけではありません',
      ),
      body: tr(
        context,
        es: 'Las entradas al museo solo las querían Noa y Marta, así que esa línea se reparte entre dos: 12 € cada una. Brais y Leo no pagan ni un céntimo de ella. El reparto se ajusta línea a línea, no por gasto entero.',
        en: 'Only Noa and Marta wanted the museum tickets, so that line is split between two: 12 € each. Brais and Leo pay nothing towards it. The split is adjusted line by line, not per whole expense.',
        gl: 'As entradas ao museo só as querían Noa e Marta, así que esa liña repártese entre dúas: 12 € cada unha. Brais e Leo non pagan nada dela.',
        ca: 'Les entrades al museu només les volien la Noa i la Marta, així que la línia es reparteix entre dues: 12 € cadascuna.',
        eu: 'Museoko sarrerak Noak eta Martak baino ez zituzten nahi, beraz lerro hori biren artean banatzen da: 12 € bakoitzak.',
        fr: 'Seules Noa et Marta voulaient les billets du musée : cette ligne se partage à deux, 12 € chacune.',
        it: 'I biglietti del museo li volevano solo Noa e Marta, quindi quella voce si divide fra due: 12 € a testa.',
        pt: 'Só a Noa e a Marta queriam os bilhetes do museu, por isso essa linha divide-se por duas: 12 € cada.',
        de: 'Die Museumstickets wollten nur Noa und Marta, also teilen sich diese Position zwei: je 12 €.',
        el: 'Τα εισιτήρια του μουσείου τα ήθελαν μόνο η Noa και η Marta, οπότε η γραμμή μοιράζεται στα δύο: 12 € η καθεμία.',
        ru: 'Билеты в музей хотели только Ноа и Марта, поэтому эта строка делится на двоих: по 12 €.',
        ar: 'تذاكر المتحف أرادتها Noa وMarta فقط، فتقسم على اثنتين: 12 يورو لكل منهما.',
        zh: '博物馆门票只有 Noa 和 Marta 想去，这一项就由两人平分，各 12 €。',
        ja: '美術館のチケットは Noa と Marta だけ。この行は 2 人で分け、各 12 € です。',
      ),
    ),

    // 6 ------------------------------------------------------------------
    TourStep(
      icon: Icons.account_balance_wallet_rounded,
      targetKey: anclas.navegacion,
      radius: 28,
      padding: 4,
      onEnter: () => onSelectTab(TourTabs.balanceGlobal),
      illustration: const TourBalancesExample(),
      title: tr(
        context,
        es: 'Y así queda la cuenta',
        en: 'And this is how it adds up',
        gl: 'E así queda a conta',
        ca: 'I així queda el compte',
        eu: 'Eta horrela geratzen da kontua',
        fr: 'Et voilà le compte',
        it: 'Ed ecco come torna il conto',
        pt: 'E é assim que fica a conta',
        de: 'Und so steht die Rechnung',
        el: 'Και έτσι βγαίνει ο λογαριασμός',
        ru: 'И вот как сходится счёт',
        ar: 'وهكذا يخرج الحساب',
        zh: '账就是这样算出来的',
        ja: '計算するとこうなります',
      ),
      body: tr(
        context,
        es: 'Brais adelantó la cena y le deben 36 €. Leo puso la gasolina y le deben 12 €. Noa y Marta pagaron menos de lo que consumieron, así que deben. Nadie ha tenido que calcular nada.',
        en: 'Brais fronted the dinner and is owed 36 €. Leo covered the fuel and is owed 12 €. Noa and Marta paid less than they consumed, so they owe. Nobody had to work anything out.',
        gl: 'Brais adiantou a cea e débenlle 36 €. Leo puxo a gasolina e débenlle 12 €. Noa e Marta pagaron menos do que consumiron, así que deben.',
        ca: 'En Brais va avançar el sopar i li deuen 36 €. En Leo va posar la benzina i li deuen 12 €.',
        eu: 'Braisek afaria aurreratu zuen eta 36 € zor diote. Leok gasolina jarri zuen eta 12 € zor diote.',
        fr: 'Brais a avancé le dîner : on lui doit 36 €. Leo a payé l essence : on lui doit 12 €.',
        it: 'Brais ha anticipato la cena e gli devono 36 €. Leo ha messo la benzina e gli devono 12 €.',
        pt: 'O Brais adiantou o jantar e devem-lhe 36 €. O Leo pôs a gasolina e devem-lhe 12 €.',
        de: 'Brais hat das Abendessen ausgelegt und bekommt 36 €. Leo hat getankt und bekommt 12 €.',
        el: 'Ο Brais πλήρωσε το δείπνο και του χρωστούν 36 €. Ο Leo έβαλε βενζίνη και του χρωστούν 12 €.',
        ru: 'Брайс оплатил ужин — ему должны 36 €. Лео заправил машину — ему должны 12 €.',
        ar: 'دفع Brais العشاء وله 36 يورو. وضع Leo البنزين وله 12 يورو.',
        zh: 'Brais 垫了晚饭，应收 36 €。Leo 加了油，应收 12 €。Noa 和 Marta 付得比消费少，所以要还钱。',
        ja: 'Brais は夕食を立て替えて 36 € の受取。Leo は給油して 12 € の受取。Noa と Marta は使った分より少なく払ったので支払い側です。',
      ),
    ),

    // 7 ------------------------------------------------------------------
    TourStep(
      icon: Icons.account_tree_rounded,
      targetKey: anclas.navegacion,
      radius: 28,
      padding: 4,
      illustration: const TourSettlementExample(),
      title: tr(
        context,
        es: 'Y con dos pagos, a cero',
        en: 'And two payments clear it',
        gl: 'E con dous pagos, a cero',
        ca: 'I amb dos pagaments, a zero',
        eu: 'Eta bi ordainketarekin, zerora',
        fr: 'Et deux paiements suffisent',
        it: 'E con due pagamenti, a zero',
        pt: 'E com dois pagamentos, a zero',
        de: 'Und mit zwei Zahlungen auf null',
        el: 'Και με δύο πληρωμές, στο μηδέν',
        ru: 'И два перевода обнуляют всё',
        ar: 'وبدفعتين يصبح كل شيء صفرا',
        zh: '两笔转账就清零',
        ja: '2 回の支払いでゼロに',
      ),
      body: tr(
        context,
        es: 'En este grupo hay cinco deudas sueltas por 54 €. ShardPay las cruza y propone dos pagos por 48 €: exactamente el mismo dinero para cada uno, en menos transferencias. Cuando alguien pague, pulsa «Reembolsar» y el plan se recalcula solo.',
        en: 'This group has five separate debts adding up to 54 €. ShardPay nets them and proposes two payments of 48 €: exactly the same money for everyone, in fewer transfers. When someone pays, tap "Reimburse" and the plan recalculates itself.',
        gl: 'Neste grupo hai cinco débedas soltas por 54 €. ShardPay crúzaas e propón dous pagos por 48 €: o mesmo diñeiro para cada un, en menos transferencias.',
        ca: 'En aquest grup hi ha cinc deutes solts per 54 €. ShardPay els creua i proposa dos pagaments per 48 €: els mateixos diners, en menys transferències.',
        eu: 'Talde honetan bost zor solte daude, 54 €. ShardPay-k gurutzatu eta bi ordainketa proposatzen ditu, 48 €: diru bera, transferentzia gutxiagorekin.',
        fr: 'Ce groupe compte cinq dettes distinctes pour 54 €. ShardPay les compense et propose deux paiements pour 48 € : le même argent pour chacun, en moins de virements.',
        it: 'In questo gruppo ci sono cinque debiti separati per 54 €. ShardPay li compensa e propone due pagamenti da 48 €: gli stessi soldi, con meno bonifici.',
        pt: 'Neste grupo há cinco dívidas soltas de 54 €. O ShardPay cruza-as e propõe dois pagamentos de 48 €: o mesmo dinheiro, em menos transferências.',
        de: 'In dieser Gruppe gibt es fünf einzelne Schulden über 54 €. ShardPay verrechnet sie und schlägt zwei Zahlungen über 48 € vor: dasselbe Geld, weniger Überweisungen.',
        el: 'Σε αυτή την ομάδα υπάρχουν πέντε χωριστά χρέη 54 €. Το ShardPay τα συμψηφίζει και προτείνει δύο πληρωμές 48 €: τα ίδια χρήματα, με λιγότερες μεταφορές.',
        ru: 'В этой группе пять отдельных долгов на 54 €. ShardPay их взаимозачитывает и предлагает два перевода на 48 €: те же деньги, но меньше переводов.',
        ar: 'في هذه المجموعة خمسة ديون منفصلة بقيمة 54 يورو. يقوم ShardPay بمقاصتها ويقترح دفعتين بقيمة 48 يورو: المال نفسه بتحويلات أقل.',
        zh: '这个群组有五笔零散欠款，合计 54 €。ShardPay 对冲后只提两笔、共 48 €：每个人的钱分毫不差，转账却少了。',
        ja: 'このグループには 54 € 分の債務が 5 件あります。ShardPay は相殺して 48 € の 2 回にまとめます。金額は各自まったく同じで、送金だけが減ります。',
      ),
    ),

    // 8 ------------------------------------------------------------------
    TourStep(
      icon: Icons.query_stats_rounded,
      targetKey: anclas.navegacion,
      radius: 28,
      padding: 4,
      onEnter: () => onSelectTab(TourTabs.estadisticas),
      title: tr(
        context,
        es: 'En qué se fue el dinero',
        en: 'Where the money went',
        gl: 'En que se foi o diñeiro',
        ca: 'On ha anat a parar els diners',
        eu: 'Dirua zertan joan den',
        fr: 'Où est passé l argent',
        it: 'Dove sono finiti i soldi',
        pt: 'Onde foi parar o dinheiro',
        de: 'Wohin das Geld ging',
        el: 'Πού πήγαν τα λεφτά',
        ru: 'Куда ушли деньги',
        ar: 'أين ذهبت النقود',
        zh: '钱都花在哪了',
        ja: 'お金の行き先',
      ),
      body: tr(
        context,
        es: 'De los 216 € del viaje: 84 € en comida, 60 € en transporte, 48 € en súper y 24 € en ocio. Aquí ves el reparto por categorías, la evolución por meses y quién adelanta más dinero. Puedes combinar varios grupos a la vez.',
        en: 'Of the 216 € trip: 84 € on food, 60 € on transport, 48 € on groceries and 24 € on leisure. Here you get the category breakdown, the month-by-month trend and who fronts the most money. You can combine several groups at once.',
        gl: 'Dos 216 € da viaxe: 84 € en comida, 60 € en transporte, 48 € no súper e 24 € en ocio. Aquí ves o reparto por categorías e quen adianta máis diñeiro.',
        ca: 'Dels 216 € del viatge: 84 € en menjar, 60 € en transport, 48 € al súper i 24 € en oci.',
        eu: 'Bidaiaren 216 €-etatik: 84 € janarian, 60 € garraioan, 48 € supermerkatuan eta 24 € aisian.',
        fr: 'Sur les 216 € du voyage : 84 € de repas, 60 € de transport, 48 € de courses et 24 € de loisirs.',
        it: 'Dei 216 € del viaggio: 84 € di cibo, 60 € di trasporto, 48 € di spesa e 24 € di svago.',
        pt: 'Dos 216 € da viagem: 84 € em comida, 60 € em transporte, 48 € no supermercado e 24 € em lazer.',
        de: 'Von den 216 € der Reise: 84 € Essen, 60 € Transport, 48 € Einkauf und 24 € Freizeit.',
        el: 'Από τα 216 € του ταξιδιού: 84 € φαγητό, 60 € μεταφορικά, 48 € σούπερ μάρκετ και 24 € διασκέδαση.',
        ru: 'Из 216 € поездки: 84 € еда, 60 € транспорт, 48 € продукты и 24 € досуг.',
        ar: 'من أصل 216 يورو للرحلة: 84 للطعام و60 للتنقل و48 للتسوق و24 للترفيه.',
        zh: '这趟 216 € 里：餐饮 84 €、交通 60 €、超市 48 €、娱乐 24 €。',
        ja: '旅行の 216 € の内訳は、食事 84 €、交通 60 €、買い物 48 €、娯楽 24 € です。',
      ),
    ),

    // 9 ------------------------------------------------------------------
    TourStep(
      icon: Icons.photo_camera_rounded,
      targetKey: anclas.navegacion,
      radius: 28,
      padding: 4,
      onEnter: () => onSelectTab(TourTabs.grupos),
      title: tr(
        context,
        es: 'El atajo: fotografía el ticket',
        en: 'The shortcut: photograph the receipt',
        gl: 'O atallo: fotografía o ticket',
        ca: 'La drecera: fotografia el tiquet',
        eu: 'Lasterbidea: atera tiketaren argazkia',
        fr: 'Le raccourci : photographiez le ticket',
        it: 'La scorciatoia: fotografa lo scontrino',
        pt: 'O atalho: fotografa a fatura',
        de: 'Die Abkürzung: den Beleg fotografieren',
        el: 'Η συντόμευση: φωτογράφισε την απόδειξη',
        ru: 'Короткий путь: сфотографируйте чек',
        ar: 'الاختصار: صوّر الإيصال',
        zh: '捷径：拍下小票',
        ja: '近道はレシート撮影',
      ),
      body: tr(
        context,
        es: 'Dentro de un grupo, «Ticket con cámara» lee las líneas y los importes del papel, y comprueba que la suma cuadre con el total impreso. Si no cuadra, te lo dice. Todo ocurre en tu móvil: la foto no sale de aquí.',
        en: 'Inside a group, "Receipt with camera" reads the lines and amounts off the paper and checks that they add up to the printed total. If they do not, it tells you. It all happens on your phone: the photo never leaves.',
        gl: 'Dentro dun grupo, «Ticket con cámara» le as liñas e os importes do papel e comproba que a suma cadre co total impreso. Todo ocorre no teu móbil.',
        ca: 'Dins d un grup, «Tiquet amb càmera» llegeix les línies i comprova que la suma quadri amb el total imprès.',
        eu: 'Talde baten barruan, «Tiketa kamerarekin» lerroak irakurtzen ditu eta batura inprimatutako guztizkoarekin egiaztatzen du.',
        fr: 'Dans un groupe, « Ticket avec appareil photo » lit les lignes et vérifie que la somme correspond au total imprimé.',
        it: 'Dentro un gruppo, «Scontrino con fotocamera» legge le voci e verifica che la somma torni con il totale stampato.',
        pt: 'Dentro de um grupo, «Fatura com câmara» lê as linhas e confirma que a soma bate com o total impresso.',
        de: 'In einer Gruppe liest „Beleg mit Kamera" die Positionen und prüft, ob die Summe zur gedruckten Gesamtsumme passt.',
        el: 'Μέσα σε μια ομάδα, το «Απόδειξη με κάμερα» διαβάζει τις γραμμές και ελέγχει ότι η σούμα βγαίνει.',
        ru: 'Внутри группы «Чек с камерой» считывает позиции и проверяет, сходится ли сумма с напечатанным итогом.',
        ar: 'داخل المجموعة، «إيصال بالكاميرا» يقرأ البنود ويتحقق من مطابقة المجموع للإجمالي المطبوع.',
        zh: '在群组里，「相机拍小票」会识别明细并核对合计是否与打印总额一致。全程在手机上完成。',
        ja: 'グループ内の「カメラでレシート」が明細を読み取り、印字された合計と一致するか確認します。処理は端末内で完結します。',
      ),
    ),

    // 10 -----------------------------------------------------------------
    TourStep(
      icon: Icons.search_rounded,
      targetKey: anclas.buscar,
      title: tr(
        context,
        es: 'Cuando tengas muchos grupos',
        en: 'When you have many groups',
        gl: 'Cando teñas moitos grupos',
        ca: 'Quan tinguis molts grups',
        eu: 'Talde asko dituzunean',
        fr: 'Quand vous aurez beaucoup de groupes',
        it: 'Quando avrai molti gruppi',
        pt: 'Quando tiveres muitos grupos',
        de: 'Wenn du viele Gruppen hast',
        el: 'Όταν έχεις πολλές ομάδες',
        ru: 'Когда групп станет много',
        ar: 'عندما تصبح لديك مجموعات كثيرة',
        zh: '当你有很多群组时',
        ja: 'グループが増えたら',
      ),
      body: tr(
        context,
        es: 'Busca por nombre de grupo o cambia a «Personas» para encontrar con quién compartes gastos. Útil cuando llevas el piso, el gimnasio y tres viajes a la vez.',
        en: 'Search by group name, or switch to "People" to find who you share expenses with. Handy when you are juggling the flat, the gym and three trips at once.',
        gl: 'Busca por nome de grupo ou cambia a «Persoas» para atopar con quen compartes gastos.',
        ca: 'Cerca per nom de grup o canvia a «Persones» per trobar amb qui comparteixes despeses.',
        eu: 'Bilatu taldearen izenagatik edo aldatu «Pertsonak» aukerara norekin partekatzen dituzun gastuak aurkitzeko.',
        fr: 'Cherchez par nom de groupe, ou passez à « Personnes » pour trouver avec qui vous partagez.',
        it: 'Cerca per nome del gruppo o passa a «Persone» per trovare con chi dividi le spese.',
        pt: 'Procura por nome de grupo ou muda para «Pessoas» para encontrar com quem partilhas despesas.',
        de: 'Suche nach Gruppennamen oder wechsle zu „Personen", um zu finden, mit wem du teilst.',
        el: 'Ψάξε με όνομα ομάδας ή άλλαξε σε «Άτομα» για να βρεις με ποιον μοιράζεσαι έξοδα.',
        ru: 'Ищите по названию группы или переключитесь на «Люди», чтобы найти, с кем делите расходы.',
        ar: 'ابحث باسم المجموعة أو انتقل إلى «الأشخاص» لتجد مع من تتقاسم المصاريف.',
        zh: '按群组名搜索，或切到「人员」找出你和谁在分摊。',
        ja: 'グループ名で検索するか、「人」に切り替えて誰と分担しているかを探せます。',
      ),
    ),

    // 11 -----------------------------------------------------------------
    TourStep(
      icon: Icons.check_circle_rounded,
      title: tr(
        context,
        es: 'Ya está',
        en: 'That is it',
        gl: 'Xa está',
        ca: 'Ja està',
        eu: 'Hori da dena',
        fr: 'C est tout',
        it: 'Tutto qui',
        pt: 'É só isso',
        de: 'Das war es',
        el: 'Αυτό ήταν',
        ru: 'Вот и всё',
        ar: 'هذا كل شيء',
        zh: '就这些',
        ja: '以上です',
      ),
      body: tr(
        context,
        es: 'La app es gratuita, sin anuncios y no recoge tus datos. En Ajustes tienes el tema, el idioma, la copia de seguridad de tus datos, este tour otra vez y la ayuda completa.',
        en: 'The app is free, has no ads and does not collect your data. Settings has the theme, the language, the backup of your data, this tour again and the full help.',
        gl: 'A app é gratuíta, sen anuncios e non recolle os teus datos. En Axustes tes o tema, o idioma, a copia dos teus datos, este tour outra vez e a axuda completa.',
        ca: 'L app és gratuïta, sense anuncis i no recull les teves dades. Als Ajustos hi ha el tema, l idioma, la còpia i aquest tour.',
        eu: 'Appa doakoa da, iragarkirik gabe eta ez ditu zure datuak biltzen. Ezarpenetan gaia, hizkuntza, kopia eta bisita hau dituzu.',
        fr: 'L application est gratuite, sans publicité et ne collecte pas vos données. Les réglages contiennent le thème, la langue, la sauvegarde et cette visite.',
        it: 'L app è gratuita, senza pubblicità e non raccoglie i tuoi dati. Nelle impostazioni trovi tema, lingua, copia e questo tour.',
        pt: 'A app é gratuita, sem anúncios e não recolhe os teus dados. Nas definições tens tema, idioma, cópia e esta visita.',
        de: 'Die App ist kostenlos, werbefrei und sammelt keine Daten. In den Einstellungen findest du Thema, Sprache, Sicherung und diese Tour.',
        el: 'Η εφαρμογή είναι δωρεάν, χωρίς διαφημίσεις και δεν συλλέγει δεδομένα. Στις ρυθμίσεις θα βρεις θέμα, γλώσσα, αντίγραφο και αυτή την ξενάγηση.',
        ru: 'Приложение бесплатное, без рекламы и не собирает ваши данные. В настройках — тема, язык, резервная копия и этот тур.',
        ar: 'التطبيق مجاني وبلا إعلانات ولا يجمع بياناتك. في الإعدادات تجد السمة واللغة والنسخة الاحتياطية وهذه الجولة.',
        zh: '本应用免费、无广告，也不收集你的数据。设置里有主题、语言、数据备份、本导览和完整帮助。',
        ja: 'このアプリは無料・広告なしで、データも収集しません。設定にはテーマ・言語・バックアップ・このツアー・詳しいヘルプがあります。',
      ),
    ),
  ];
}
