import 'package:flutter/material.dart';

String tr(
  BuildContext context, {
  required String es,
  String? en,
  String? gl,
  String? fr,
  String? it,
  String? pt,
  String? de,
  String? ru,
  String? zh,
  String? ja,
}) {
  final languageCode = Localizations.localeOf(context).languageCode;
  final fallback = en ?? es;

  switch (Localizations.localeOf(context).languageCode) {
    case 'en':
      return en ?? es;
    case 'de':
      return de ?? _translateWithFallback(languageCode, fallback);
    case 'ru':
      return ru ?? _translateWithFallback(languageCode, fallback);
    case 'zh':
      return zh ?? _translateWithFallback(languageCode, fallback);
    case 'ja':
      return ja ?? _translateWithFallback(languageCode, fallback);
    case 'gl':
      return gl ?? es;
    case 'fr':
      return fr ?? es;
    case 'it':
      return it ?? es;
    case 'pt':
      return pt ?? es;
    case 'es':
    default:
      return es;
  }
}

String localeTag(BuildContext context) => Localizations.localeOf(context).toLanguageTag();

String _translateWithFallback(String languageCode, String fallback) {
  final direct = _localizedByEnglish[languageCode]?[fallback];
  if (direct != null) {
    return direct;
  }

  for (final pattern in _patternTranslations) {
    final translated = pattern.translate(languageCode, fallback);
    if (translated != null) {
      return translated;
    }
  }

  return fallback;
}

class _PatternTranslation {
  const _PatternTranslation(this.pattern, this.builders);

  final RegExp pattern;
  final Map<String, String Function(RegExpMatch match)> builders;

  String? translate(String languageCode, String value) {
    final builder = builders[languageCode];
    if (builder == null) {
      return null;
    }
    final match = pattern.firstMatch(value);
    if (match == null) {
      return null;
    }
    return builder(match);
  }
}

final Map<String, Map<String, String>> _localizedByEnglish = {
  'de': _deTranslations,
  'ru': _ruTranslations,
  'zh': _zhTranslations,
  'ja': _jaTranslations,
};

final List<_PatternTranslation> _patternTranslations = [
  _PatternTranslation(
    RegExp(r'^Account created: (.+)$'),
    {
      'de': (match) => 'Konto erstellt: ${match.group(1)!}',
      'ru': (match) => 'Аккаунт создан: ${match.group(1)!}',
      'zh': (match) => '账户创建于：${match.group(1)!}',
      'ja': (match) => 'アカウント作成日: ${match.group(1)!}',
    },
  ),
  _PatternTranslation(
    RegExp(r'^(\d+) members · invite (.+)$'),
    {
      'de': (match) => '${match.group(1)!} Mitglieder · Einladung ${match.group(2)!}',
      'ru': (match) => '${match.group(1)!} участников · код ${match.group(2)!}',
      'zh': (match) => '${match.group(1)!} 位成员 · 邀请码 ${match.group(2)!}',
      'ja': (match) => '${match.group(1)!} 人のメンバー・招待コード ${match.group(2)!}',
    },
  ),
  _PatternTranslation(
    RegExp(r'^(\d+) members · invite (.+) · updated (.+)$'),
    {
      'de': (match) => '${match.group(1)!} Mitglieder · Einladung ${match.group(2)!} · aktualisiert ${match.group(3)!}',
      'ru': (match) => '${match.group(1)!} участников · код ${match.group(2)!} · обновлено ${match.group(3)!}',
      'zh': (match) => '${match.group(1)!} 位成员 · 邀请码 ${match.group(2)!} · 更新于 ${match.group(3)!}',
      'ja': (match) => '${match.group(1)!} 人のメンバー・招待コード ${match.group(2)!} ・更新 ${match.group(3)!}',
    },
  ),
  _PatternTranslation(
    RegExp(r'^You owe (.+) in this group\.$'),
    {
      'de': (match) => 'Du schuldest in dieser Gruppe ${match.group(1)!}.',
      'ru': (match) => 'Вы должны ${match.group(1)!} в этой группе.',
      'zh': (match) => '你在此群组中需支付 ${match.group(1)!}。',
      'ja': (match) => 'このグループで ${match.group(1)!} を支払う必要があります。',
    },
  ),
  _PatternTranslation(
    RegExp(r'^You are owed (.+) in this group\.$'),
    {
      'de': (match) => 'Dir schuldet man in dieser Gruppe ${match.group(1)!}.',
      'ru': (match) => 'В этой группе вам должны ${match.group(1)!}.',
      'zh': (match) => '在此群组中，有人欠你 ${match.group(1)!}。',
      'ja': (match) => 'このグループでは ${match.group(1)!} を受け取る予定です。',
    },
  ),
  _PatternTranslation(
    RegExp(r'^Direct settlement between (.+) and (.+)\.$'),
    {
      'de': (match) => 'Direkte Verrechnung zwischen ${match.group(1)!} und ${match.group(2)!}.',
      'ru': (match) => 'Прямой расчет между ${match.group(1)!} и ${match.group(2)!}.',
      'zh': (match) => '${match.group(1)!} 与 ${match.group(2)!} 之间的直接结算。',
      'ja': (match) => '${match.group(1)!} と ${match.group(2)!} の直接精算です。',
    },
  ),
  _PatternTranslation(
    RegExp(r'^Reimbursement to (.+)$'),
    {
      'de': (match) => 'Erstattung an ${match.group(1)!}',
      'ru': (match) => 'Возмещение для ${match.group(1)!}',
      'zh': (match) => '向 ${match.group(1)!} 退款',
      'ja': (match) => '${match.group(1)!} への返済',
    },
  ),
  _PatternTranslation(
    RegExp(r'^Join (.+) on ShardPay$'),
    {
      'de': (match) => 'Tritt ${match.group(1)!} in ShardPay bei',
      'ru': (match) => 'Присоединяйтесь к ${match.group(1)!} в ShardPay',
      'zh': (match) => '在 ShardPay 中加入 ${match.group(1)!}',
      'ja': (match) => 'ShardPay で ${match.group(1)!} に参加',
    },
  ),
  _PatternTranslation(
    RegExp(r'^You joined (.+)\.$'),
    {
      'de': (match) => 'Du bist ${match.group(1)!} beigetreten.',
      'ru': (match) => 'Вы присоединились к ${match.group(1)!}.',
      'zh': (match) => '你已加入 ${match.group(1)!}。',
      'ja': (match) => '${match.group(1)!} に参加しました。',
    },
  ),
  _PatternTranslation(
    RegExp(r'^"(.+)" will be deleted and will no longer count in balances or charts\.$'),
    {
      'de': (match) => '"${match.group(1)!}" wird gelöscht und erscheint nicht mehr in Salden oder Diagrammen.',
      'ru': (match) => '"${match.group(1)!}" будет удален и больше не появится в балансах и графиках.',
      'zh': (match) => '“${match.group(1)!}” 将被删除，并且不会再计入余额或图表。',
      'ja': (match) => '「${match.group(1)!}」は削除され、残高やグラフには反映されなくなります。',
    },
  ),
  _PatternTranslation(
    RegExp(r'^Hi, (.+)$'),
    {
      'de': (match) => 'Hallo, ${match.group(1)!}',
      'ru': (match) => 'Привет, ${match.group(1)!}',
      'zh': (match) => '你好，${match.group(1)!}',
      'ja': (match) => 'こんにちは、${match.group(1)!}',
    },
  ),
  _PatternTranslation(
    RegExp(r'^User ID: (.+)$'),
    {
      'de': (match) => 'Benutzer-ID: ${match.group(1)!}',
      'ru': (match) => 'ID пользователя: ${match.group(1)!}',
      'zh': (match) => '用户 ID：${match.group(1)!}',
      'ja': (match) => 'ユーザー ID: ${match.group(1)!}',
    },
  ),
  _PatternTranslation(
    RegExp(r'^(\d+) unread$'),
    {
      'de': (match) => '${match.group(1)!} ungelesen',
      'ru': (match) => '${match.group(1)!} непрочитанных',
      'zh': (match) => '${match.group(1)!} 条未读',
      'ja': (match) => '未読 ${match.group(1)!} 件',
    },
  ),
  _PatternTranslation(
    RegExp(r'^Who are you in (.+)\?$'),
    {
      'de': (match) => 'Wer bist du in ${match.group(1)!}?',
      'ru': (match) => 'Кто вы в ${match.group(1)!}?',
      'zh': (match) => '你在 ${match.group(1)!} 中是谁？',
      'ja': (match) => '${match.group(1)!} では誰として参加しますか？',
    },
  ),
  _PatternTranslation(
    RegExp(r'^Join as (.+)$'),
    {
      'de': (match) => 'Beitreten als ${match.group(1)!}',
      'ru': (match) => 'Войти как ${match.group(1)!}',
      'zh': (match) => '以 ${match.group(1)!} 身份加入',
      'ja': (match) => '${match.group(1)!} として参加',
    },
  ),
  _PatternTranslation(
    RegExp(r'^Sign-in failed\. (.+)$'),
    {
      'de': (match) => 'Anmeldung fehlgeschlagen. ${match.group(1)!}',
      'ru': (match) => 'Не удалось войти. ${match.group(1)!}',
      'zh': (match) => '登录失败。${match.group(1)!}',
      'ja': (match) => 'サインインに失敗しました。${match.group(1)!}',
    },
  ),
];

const Map<String, String> _deTranslations = {
  'Quick manual': 'Schnellanleitung',
  '1. Create or join groups': '1. Gruppen erstellen oder beitreten',
  '2. Add expenses or reimbursements': '2. Ausgaben oder Erstattungen hinzufügen',
  '3. Review notifications and balances': '3. Benachrichtigungen und Salden prüfen',
  'Notifications': 'Benachrichtigungen',
  'There are no notifications with the current filters.': 'Mit den aktuellen Filtern gibt es keine Benachrichtigungen.',
  'You have no pending debts or claims with real accounts across your groups.': 'Du hast gruppenübergreifend keine offenen Schulden oder Forderungen mit echten Konten.',
  'No pending debts or claims with real accounts across your groups.': 'Du hast gruppenübergreifend keine offenen Schulden oder Forderungen mit echten Konten.',
  'Owes you money': 'Schuldet dir Geld',
  'You owe money': 'Du schuldest Geld',
  'Groups': 'Gruppen',
  'Global balance': 'Globaler Saldo',
  'Stats': 'Statistiken',
  'Request': 'Anfordern',
  'Reimburse': 'Erstatten',
  'Record reimbursement': 'Erstattung erfassen',
  'Amount': 'Betrag',
  'Cancel': 'Abbrechen',
  'Save': 'Speichern',
  'Reimbursement': 'Erstattung',
  'Request reimbursement': 'Erstattung anfordern',
  'Send': 'Senden',
  'Add expense': 'Ausgabe hinzufügen',
  'This group is closed. You can only review it until an admin reopens it.': 'Diese Gruppe ist geschlossen. Du kannst sie nur ansehen, bis ein Admin sie wieder öffnet.',
  'Expense summary': 'Ausgabenübersicht',
  'Main concept': 'Haupttitel',
  'Dinner, fuel, groceries...': 'Abendessen, Tanken, Einkauf...',
  'Total amount': 'Gesamtbetrag',
  'Optional note': 'Optionale Notiz',
  'Payer and category': 'Zahlende Person und Kategorie',
  'Paid by': 'Bezahlt von',
  'pending': 'ausstehend',
  'Category': 'Kategorie',
  'Who takes part': 'Wer beteiligt sich',
  'Select the people who share this expense.': 'Wähle die Personen aus, die diese Ausgabe teilen.',
  'Pending to link': 'Wartet auf Verknüpfung',
  'Save expense': 'Ausgabe speichern',
  'Check the concept, amount and selected participants.': 'Prüfe Titel, Betrag und ausgewählte Teilnehmende.',
  'Group not found.': 'Gruppe nicht gefunden.',
  'Group settings': 'Gruppeneinstellungen',
  'Reopen group': 'Gruppe wieder öffnen',
  'Close group': 'Gruppe schließen',
  'Transfer admin': 'Admin übertragen',
  'Leave group': 'Gruppe verlassen',
  'Delete group': 'Gruppe löschen',
  'Overview': 'Übersicht',
  'Balance': 'Saldo',
  'Expenses': 'Ausgaben',
  'Charts': 'Diagramme',
  'Expense saved.': 'Ausgabe gespeichert.',
  'Share link': 'Link teilen',
  'Group name': 'Gruppenname',
  'Description': 'Beschreibung',
  'Add': 'Hinzufügen',
  'Review receipt': 'Beleg prüfen',
  'Item': 'Posten',
  'Adjust split': 'Aufteilung anpassen',
  'Save receipt': 'Beleg speichern',
  'Edit expense': 'Ausgabe bearbeiten',
  'Note': 'Notiz',
  'Items': 'Posten',
  'Delete item': 'Posten löschen',
  'Add item': 'Posten hinzufügen',
  'Save changes': 'Änderungen speichern',
  'Delete expense': 'Ausgabe löschen',
  'Advanced split': 'Erweiterte Aufteilung',
  'Equal split': 'Gleichmäßig',
  'The percentage sum must be 100%.': 'Die Summe der Prozentsätze muss 100 % ergeben.',
  'Close': 'Schließen',
  'Reopen': 'Wieder öffnen',
  'Group closed.': 'Gruppe geschlossen.',
  'Group reopened.': 'Gruppe wieder geöffnet.',
  'The group is closed. It is available in read-only mode.': 'Die Gruppe ist geschlossen. Sie ist nur im Lesemodus verfügbar.',
  'Group total': 'Gruppensumme',
  'Your balance': 'Dein Saldo',
  'Members': 'Mitglieder',
  'This group is closed and can only be viewed. The admin can reopen it from the top menu.': 'Diese Gruppe ist geschlossen und nur lesbar. Der Admin kann sie oben im Menü wieder öffnen.',
  'Group dates': 'Gruppendaten',
  'Created': 'Erstellt',
  'Last update': 'Letzte Änderung',
  'Closed at': 'Geschlossen am',
  'No active closure': 'Keine aktive Schließung',
  'Quick actions': 'Schnellaktionen',
  'Invite': 'Einladen',
  'Categories': 'Kategorien',
  'People and access': 'Personen und Zugriff',
  'Upload receipt': 'Beleg hochladen',
  'Receipt with camera': 'Beleg mit Kamera',
  'Settings': 'Einstellungen',
  'Group': 'Gruppe',
  'Search groups': 'Gruppen suchen',
  'Search people': 'Personen suchen',
  'People': 'Personen',
  'Join with link or QR': 'Per Link oder QR beitreten',
  'You do not have groups yet. Create one or join with an invite.': 'Du hast noch keine Gruppen. Erstelle eine oder tritt per Einladung bei.',
  'No groups match your search.': 'Keine Gruppen entsprechen deiner Suche.',
  'Closed group': 'Geschlossene Gruppe',
  'Open group': 'Gruppe öffnen',
  'Spent': 'Ausgegeben',
  'Share invite': 'Einladung teilen',
  'Create group': 'Gruppe erstellen',
  'Currency': 'Währung',
  'Pending people': 'Ausstehende Personen',
  'Add people even if they do not have an account yet. They can link themselves from the invite later.': 'Füge Personen hinzu, auch wenn sie noch kein Konto haben. Sie können sich später über die Einladung verknüpfen.',
  'Pending name': 'Ausstehender Name',
  'Create': 'Erstellen',
  'Group created.': 'Gruppe erstellt.',
  'Paste group link or code': 'Gruppenlink oder Code einfügen',
  'Scan QR': 'QR scannen',
  'Continue': 'Weiter',
  'No group was found for that invite.': 'Für diese Einladung wurde keine Gruppe gefunden.',
  'You can join with your current profile or pick one of the prepared names.': 'Du kannst mit deinem aktuellen Profil beitreten oder einen vorbereiteten Namen wählen.',
  'Choose one of the names prepared by the admin to link your access.': 'Wähle einen der vom Admin vorbereiteten Namen, um deinen Zugang zu verknüpfen.',
  'Prepared by the admin': 'Vom Admin vorbereitet',
  'Use this identity': 'Diese Identität verwenden',
  'Theme': 'Thema',
  'Choose one palette for the whole app.': 'Wähle eine Farbpalette für die ganze App.',
  'Visual mode': 'Darstellungsmodus',
  'dark': 'dunkel',
  'light': 'hell',
  'Language': 'Sprache',
  'Change interface and formatting language.': 'Sprache der Oberfläche und Formatierung ändern.',
  'Active language': 'Aktive Sprache',
  'New expenses': 'Neue Ausgaben',
  'Recorded reimbursements': 'Erfasste Erstattungen',
  'Reimbursement requests': 'Erstattungsanfragen',
  'Open notification center': 'Benachrichtigungszentrale öffnen',
  'Manual': 'Anleitung',
  'You can reopen the quick guide whenever you want.': 'Du kannst die Schnellanleitung jederzeit wieder öffnen.',
  'Sign out': 'Abmelden',
  'Delete': 'Löschen',
  'Active chart': 'Aktives Diagramm',
  'Select a view': 'Ansicht auswählen',
  'Where money moves, ShardPay turns it into signal.': 'Wo Geld fließt, macht ShardPay daraus Klarheit.',
  'Total spend': 'Gesamtausgaben',
  'Entries': 'Einträge',
  'Visible people': 'Sichtbare Personen',
  'Not enough data yet.': 'Noch nicht genügend Daten.',
  'There are no groups with spend yet.': 'Es gibt noch keine Gruppen mit Ausgaben.',
  'There are no months with spend yet.': 'Es gibt noch keine Monate mit Ausgaben.',
  'There are no people with registered spend yet.': 'Es gibt noch keine Personen mit erfassten Ausgaben.',
  'Distribution by category': 'Verteilung nach Kategorie',
  'Which groups move the most spend': 'Welche Gruppen die meisten Ausgaben bewegen',
  'Monthly spend': 'Monatliche Ausgaben',
  'Who is advancing the most': 'Wer am meisten auslegt',
  'You are in local demo mode because Firebase credentials are missing in --dart-define. The app remains fully navigable.': 'Du bist im lokalen Demo-Modus, weil Firebase-Zugangsdaten in --dart-define fehlen. Die App bleibt vollständig nutzbar.',
  'Share expenses with style: scan receipts, split each item precisely, and join groups by QR or link.': 'Teile Ausgaben stilvoll: Scanne Belege, teile jeden Posten exakt auf und tritt per QR oder Link Gruppen bei.',
  'Shared groups': 'Geteilte Gruppen',
  'Receipt OCR': 'Beleg-OCR',
  'Exact split': 'Exakte Aufteilung',
  'QR invites': 'QR-Einladungen',
  'Create your account in under a minute': 'Erstelle dein Konto in unter einer Minute',
  'Return to your groups and balances': 'Zurück zu deinen Gruppen und Salden',
  'Prepare your account to share expenses, receipts and advanced splits from day one.': 'Bereite dein Konto vor, um ab dem ersten Tag Ausgaben, Belege und erweiterte Aufteilungen zu teilen.',
  'Use email or Google to recover groups, invites and pending activity.': 'Nutze E-Mail oder Google, um Gruppen, Einladungen und offene Aktivitäten wiederzufinden.',
  'I already have an account': 'Ich habe bereits ein Konto',
  'I am new here': 'Ich bin neu hier',
  'How should we call you': 'Wie sollen wir dich nennen',
  'Visible name for your group': 'Sichtbarer Name für deine Gruppe',
  'Enter the name you want to show.': 'Gib den Namen ein, der angezeigt werden soll.',
  'Your email': 'Deine E-Mail',
  'Enter your email.': 'Gib deine E-Mail ein.',
  'Check the email format.': 'Prüfe das E-Mail-Format.',
  'Create a password': 'Passwort erstellen',
  'Your password': 'Dein Passwort',
  'At least 6 characters': 'Mindestens 6 Zeichen',
  'Type your password': 'Gib dein Passwort ein',
  'Enter your password.': 'Gib dein Passwort ein.',
  'Use at least 6 characters.': 'Verwende mindestens 6 Zeichen.',
  'You will create your account with email. Google can be used later as soon as infrastructure is active.': 'Du erstellst dein Konto per E-Mail. Google kann später genutzt werden, sobald die Infrastruktur aktiv ist.',
  'If you do not have access yet, switch to the new account mode and create it here.': 'Wenn du noch keinen Zugang hast, wechsle in den Modus für neue Konten und erstelle ihn hier.',
  'Create account and enter': 'Konto erstellen und starten',
  'Continue with email': 'Mit E-Mail fortfahren',
  'Continue with Google': 'Mit Google fortfahren',
  'Access is not yet enabled in Google Cloud for this project. Billing/Auth still needs activation.': 'Der Zugriff ist in Google Cloud für dieses Projekt noch nicht aktiviert. Billing/Auth muss noch aktiviert werden.',
  'Could not reach the server. Check your connection and try again.': 'Der Server konnte nicht erreicht werden. Prüfe deine Verbindung und versuche es erneut.',
  'Open manual': 'Anleitung öffnen',
  'Delete profile': 'Profil löschen',
  'Your account will be deleted. Your group participation will remain archived to preserve history.': 'Dein Konto wird gelöscht. Deine Gruppenbeteiligungen bleiben archiviert, damit die Historie erhalten bleibt.',
  'Check the items detected on the receipt.': 'Prüfe die auf dem Beleg erkannten Posten.',
};

const Map<String, String> _ruTranslations = {
  'Quick manual': 'Краткое руководство',
  '1. Create or join groups': '1. Создавайте группы или вступайте в них',
  '2. Add expenses or reimbursements': '2. Добавляйте расходы или возмещения',
  '3. Review notifications and balances': '3. Проверяйте уведомления и балансы',
  'Notifications': 'Уведомления',
  'There are no notifications with the current filters.': 'С текущими фильтрами уведомлений нет.',
  'You have no pending debts or claims with real accounts across your groups.': 'Во всех ваших группах нет незакрытых долгов или требований по реальным аккаунтам.',
  'No pending debts or claims with real accounts across your groups.': 'Во всех ваших группах нет незакрытых долгов или требований по реальным аккаунтам.',
  'Owes you money': 'Должен вам деньги',
  'You owe money': 'Вы должны деньги',
  'Groups': 'Группы',
  'Global balance': 'Общий баланс',
  'Stats': 'Статистика',
  'Request': 'Запросить',
  'Reimburse': 'Возместить',
  'Record reimbursement': 'Зарегистрировать возмещение',
  'Amount': 'Сумма',
  'Cancel': 'Отмена',
  'Save': 'Сохранить',
  'Reimbursement': 'Возмещение',
  'Request reimbursement': 'Запросить возмещение',
  'Send': 'Отправить',
  'Add expense': 'Добавить расход',
  'This group is closed. You can only review it until an admin reopens it.': 'Эта группа закрыта. Просмотр доступен, пока администратор не откроет её снова.',
  'Expense summary': 'Сводка расхода',
  'Main concept': 'Основное название',
  'Dinner, fuel, groceries...': 'Ужин, топливо, покупки...',
  'Total amount': 'Общая сумма',
  'Optional note': 'Необязательная заметка',
  'Payer and category': 'Плательщик и категория',
  'Paid by': 'Оплатил',
  'pending': 'ожидает',
  'Category': 'Категория',
  'Who takes part': 'Кто участвует',
  'Select the people who share this expense.': 'Выберите людей, которые участвуют в этом расходе.',
  'Pending to link': 'Ожидает привязки',
  'Save expense': 'Сохранить расход',
  'Check the concept, amount and selected participants.': 'Проверьте название, сумму и выбранных участников.',
  'Group not found.': 'Группа не найдена.',
  'Group settings': 'Настройки группы',
  'Reopen group': 'Открыть группу снова',
  'Close group': 'Закрыть группу',
  'Transfer admin': 'Передать администратора',
  'Leave group': 'Покинуть группу',
  'Delete group': 'Удалить группу',
  'Overview': 'Обзор',
  'Balance': 'Баланс',
  'Expenses': 'Расходы',
  'Charts': 'Графики',
  'Expense saved.': 'Расход сохранён.',
  'Share link': 'Поделиться ссылкой',
  'Group name': 'Название группы',
  'Description': 'Описание',
  'Add': 'Добавить',
  'Review receipt': 'Проверить чек',
  'Item': 'Позиция',
  'Adjust split': 'Изменить распределение',
  'Save receipt': 'Сохранить чек',
  'Edit expense': 'Изменить расход',
  'Note': 'Заметка',
  'Items': 'Позиции',
  'Delete item': 'Удалить позицию',
  'Add item': 'Добавить позицию',
  'Save changes': 'Сохранить изменения',
  'Delete expense': 'Удалить расход',
  'Advanced split': 'Расширенное распределение',
  'Equal split': 'Поровну',
  'The percentage sum must be 100%.': 'Сумма процентов должна быть равна 100%.',
  'Close': 'Закрыть',
  'Reopen': 'Открыть снова',
  'Group closed.': 'Группа закрыта.',
  'Group reopened.': 'Группа снова открыта.',
  'The group is closed. It is available in read-only mode.': 'Группа закрыта. Она доступна только для чтения.',
  'Group total': 'Сумма группы',
  'Your balance': 'Ваш баланс',
  'Members': 'Участники',
  'This group is closed and can only be viewed. The admin can reopen it from the top menu.': 'Эта группа закрыта и доступна только для просмотра. Администратор может открыть её снова из верхнего меню.',
  'Group dates': 'Даты группы',
  'Created': 'Создано',
  'Last update': 'Последнее обновление',
  'Closed at': 'Закрыто',
  'No active closure': 'Нет активного закрытия',
  'Quick actions': 'Быстрые действия',
  'Invite': 'Пригласить',
  'Categories': 'Категории',
  'People and access': 'Люди и доступ',
  'Upload receipt': 'Загрузить чек',
  'Receipt with camera': 'Чек с камеры',
  'Settings': 'Настройки',
  'Group': 'Группа',
  'Search groups': 'Искать группы',
  'Search people': 'Искать людей',
  'People': 'Люди',
  'Join with link or QR': 'Войти по ссылке или QR',
  'You do not have groups yet. Create one or join with an invite.': 'У вас пока нет групп. Создайте новую или присоединитесь по приглашению.',
  'No groups match your search.': 'По вашему запросу группы не найдены.',
  'Closed group': 'Закрытая группа',
  'Open group': 'Открыть группу',
  'Spent': 'Потрачено',
  'Share invite': 'Поделиться приглашением',
  'Create group': 'Создать группу',
  'Currency': 'Валюта',
  'Pending people': 'Ожидаемые участники',
  'Add people even if they do not have an account yet. They can link themselves from the invite later.': 'Добавляйте людей, даже если у них пока нет аккаунта. Позже они смогут привязаться по приглашению.',
  'Pending name': 'Ожидаемое имя',
  'Create': 'Создать',
  'Group created.': 'Группа создана.',
  'Paste group link or code': 'Вставьте ссылку или код группы',
  'Scan QR': 'Сканировать QR',
  'Continue': 'Продолжить',
  'No group was found for that invite.': 'По этому приглашению группа не найдена.',
  'You can join with your current profile or pick one of the prepared names.': 'Вы можете войти с текущим профилем или выбрать одно из подготовленных имен.',
  'Choose one of the names prepared by the admin to link your access.': 'Выберите одно из имен, подготовленных администратором, чтобы привязать доступ.',
  'Prepared by the admin': 'Подготовлено администратором',
  'Use this identity': 'Использовать эту личность',
  'Theme': 'Тема',
  'Choose one palette for the whole app.': 'Выберите одну палитру для всего приложения.',
  'Visual mode': 'Режим отображения',
  'dark': 'тёмный',
  'light': 'светлый',
  'Language': 'Язык',
  'Change interface and formatting language.': 'Изменить язык интерфейса и форматирования.',
  'Active language': 'Активный язык',
  'New expenses': 'Новые расходы',
  'Recorded reimbursements': 'Зарегистрированные возмещения',
  'Reimbursement requests': 'Запросы на возмещение',
  'Open notification center': 'Открыть центр уведомлений',
  'Manual': 'Руководство',
  'You can reopen the quick guide whenever you want.': 'Вы можете снова открыть краткое руководство в любой момент.',
  'Sign out': 'Выйти',
  'Delete': 'Удалить',
  'Active chart': 'Активный график',
  'Select a view': 'Выберите вид',
  'Where money moves, ShardPay turns it into signal.': 'Где есть движение денег, ShardPay превращает его в понятную картину.',
  'Total spend': 'Общие расходы',
  'Entries': 'Записи',
  'Visible people': 'Видимые люди',
  'Not enough data yet.': 'Пока недостаточно данных.',
  'There are no groups with spend yet.': 'Пока нет групп с расходами.',
  'There are no months with spend yet.': 'Пока нет месяцев с расходами.',
  'There are no people with registered spend yet.': 'Пока нет людей с зарегистрированными расходами.',
  'Distribution by category': 'Распределение по категориям',
  'Which groups move the most spend': 'Какие группы создают больше всего расходов',
  'Monthly spend': 'Ежемесячные расходы',
  'Who is advancing the most': 'Кто больше всех платит вперёд',
  'You are in local demo mode because Firebase credentials are missing in --dart-define. The app remains fully navigable.': 'Вы в локальном демо-режиме, потому что в --dart-define отсутствуют учетные данные Firebase. Приложение полностью доступно для навигации.',
  'Share expenses with style: scan receipts, split each item precisely, and join groups by QR or link.': 'Делите расходы удобно: сканируйте чеки, точно распределяйте каждую позицию и входите в группы по QR или ссылке.',
  'Shared groups': 'Общие группы',
  'Receipt OCR': 'OCR чека',
  'Exact split': 'Точное распределение',
  'QR invites': 'QR-приглашения',
  'Create your account in under a minute': 'Создайте аккаунт меньше чем за минуту',
  'Return to your groups and balances': 'Вернитесь к группам и балансам',
  'Prepare your account to share expenses, receipts and advanced splits from day one.': 'Подготовьте аккаунт, чтобы с первого дня делить расходы, чеки и сложные распределения.',
  'Use email or Google to recover groups, invites and pending activity.': 'Используйте email или Google, чтобы вернуть группы, приглашения и незавершенные действия.',
  'I already have an account': 'У меня уже есть аккаунт',
  'I am new here': 'Я здесь впервые',
  'How should we call you': 'Как к вам обращаться',
  'Visible name for your group': 'Отображаемое имя в группе',
  'Enter the name you want to show.': 'Введите имя, которое хотите показывать.',
  'Your email': 'Ваш email',
  'Enter your email.': 'Введите ваш email.',
  'Check the email format.': 'Проверьте формат email.',
  'Create a password': 'Создать пароль',
  'Your password': 'Ваш пароль',
  'At least 6 characters': 'Не менее 6 символов',
  'Type your password': 'Введите пароль',
  'Enter your password.': 'Введите пароль.',
  'Use at least 6 characters.': 'Используйте не менее 6 символов.',
  'You will create your account with email. Google can be used later as soon as infrastructure is active.': 'Вы создадите аккаунт по email. Google можно будет использовать позже, когда инфраструктура будет активирована.',
  'If you do not have access yet, switch to the new account mode and create it here.': 'Если у вас ещё нет доступа, переключитесь в режим нового аккаунта и создайте его здесь.',
  'Create account and enter': 'Создать аккаунт и войти',
  'Continue with email': 'Продолжить с email',
  'Continue with Google': 'Продолжить с Google',
  'Access is not yet enabled in Google Cloud for this project. Billing/Auth still needs activation.': 'Доступ к этому проекту в Google Cloud пока не включен. Billing/Auth ещё нужно активировать.',
  'Could not reach the server. Check your connection and try again.': 'Не удалось связаться с сервером. Проверьте подключение и попробуйте снова.',
  'Open manual': 'Открыть руководство',
  'Delete profile': 'Удалить профиль',
  'Your account will be deleted. Your group participation will remain archived to preserve history.': 'Ваш аккаунт будет удалён. Участие в группах останется в архиве для сохранения истории.',
  'Check the items detected on the receipt.': 'Проверьте позиции, найденные на чеке.',
};

const Map<String, String> _zhTranslations = {
  'Quick manual': '快速指南',
  '1. Create or join groups': '1. 创建或加入群组',
  '2. Add expenses or reimbursements': '2. 添加支出或报销',
  '3. Review notifications and balances': '3. 查看通知和余额',
  'Notifications': '通知',
  'There are no notifications with the current filters.': '按当前筛选条件，没有通知。',
  'You have no pending debts or claims with real accounts across your groups.': '你在所有群组中都没有与真实账户相关的待处理债务或应收款。',
  'No pending debts or claims with real accounts across your groups.': '你在所有群组中都没有与真实账户相关的待处理债务或应收款。',
  'Owes you money': '对方欠你钱',
  'You owe money': '你欠对方钱',
  'Groups': '群组',
  'Global balance': '全局余额',
  'Stats': '统计',
  'Request': '请求',
  'Reimburse': '还款',
  'Record reimbursement': '记录报销',
  'Amount': '金额',
  'Cancel': '取消',
  'Save': '保存',
  'Reimbursement': '报销',
  'Request reimbursement': '请求报销',
  'Send': '发送',
  'Add expense': '添加支出',
  'This group is closed. You can only review it until an admin reopens it.': '此群组已关闭。在管理员重新打开之前，你只能查看。',
  'Expense summary': '支出摘要',
  'Main concept': '主标题',
  'Dinner, fuel, groceries...': '晚餐、加油、采购……',
  'Total amount': '总金额',
  'Optional note': '可选备注',
  'Payer and category': '付款人和分类',
  'Paid by': '付款人',
  'pending': '待关联',
  'Category': '分类',
  'Who takes part': '参与人',
  'Select the people who share this expense.': '选择分摊此支出的人员。',
  'Pending to link': '等待关联',
  'Save expense': '保存支出',
  'Check the concept, amount and selected participants.': '请检查标题、金额和参与人。',
  'Group not found.': '未找到群组。',
  'Group settings': '群组设置',
  'Reopen group': '重新开启群组',
  'Close group': '关闭群组',
  'Transfer admin': '转移管理员',
  'Leave group': '离开群组',
  'Delete group': '删除群组',
  'Overview': '概览',
  'Balance': '余额',
  'Expenses': '支出',
  'Charts': '图表',
  'Expense saved.': '支出已保存。',
  'Share link': '分享链接',
  'Group name': '群组名称',
  'Description': '描述',
  'Add': '添加',
  'Review receipt': '检查小票',
  'Item': '条目',
  'Adjust split': '调整分摊',
  'Save receipt': '保存小票',
  'Edit expense': '编辑支出',
  'Note': '备注',
  'Items': '条目',
  'Delete item': '删除条目',
  'Add item': '添加条目',
  'Save changes': '保存更改',
  'Delete expense': '删除支出',
  'Advanced split': '高级分摊',
  'Equal split': '平均分摊',
  'The percentage sum must be 100%.': '百分比总和必须为 100%。',
  'Close': '关闭',
  'Reopen': '重新开启',
  'Group closed.': '群组已关闭。',
  'Group reopened.': '群组已重新开启。',
  'The group is closed. It is available in read-only mode.': '群组已关闭，仅可只读查看。',
  'Group total': '群组总额',
  'Your balance': '你的余额',
  'Members': '成员',
  'This group is closed and can only be viewed. The admin can reopen it from the top menu.': '此群组已关闭，只能查看。管理员可从顶部菜单重新开启。',
  'Group dates': '群组日期',
  'Created': '创建时间',
  'Last update': '最后更新',
  'Closed at': '关闭时间',
  'No active closure': '当前未关闭',
  'Quick actions': '快捷操作',
  'Invite': '邀请',
  'Categories': '分类',
  'People and access': '成员与访问',
  'Upload receipt': '上传小票',
  'Receipt with camera': '拍照识别小票',
  'Settings': '设置',
  'Group': '群组',
  'Search groups': '搜索群组',
  'Search people': '搜索成员',
  'People': '成员',
  'Join with link or QR': '通过链接或二维码加入',
  'You do not have groups yet. Create one or join with an invite.': '你还没有群组。创建一个，或通过邀请加入。',
  'No groups match your search.': '没有符合搜索条件的群组。',
  'Closed group': '已关闭群组',
  'Open group': '打开群组',
  'Spent': '已支出',
  'Share invite': '分享邀请',
  'Create group': '创建群组',
  'Currency': '货币',
  'Pending people': '待加入成员',
  'Add people even if they do not have an account yet. They can link themselves from the invite later.': '即使对方还没有账号，也可以先添加。之后他们可以通过邀请自行绑定。',
  'Pending name': '待加入姓名',
  'Create': '创建',
  'Group created.': '群组已创建。',
  'Paste group link or code': '粘贴群组链接或代码',
  'Scan QR': '扫描二维码',
  'Continue': '继续',
  'No group was found for that invite.': '未找到与该邀请对应的群组。',
  'You can join with your current profile or pick one of the prepared names.': '你可以使用当前资料加入，或选择一个已准备好的名称。',
  'Choose one of the names prepared by the admin to link your access.': '选择管理员准备好的名称之一来绑定你的访问。',
  'Prepared by the admin': '由管理员预设',
  'Use this identity': '使用此身份',
  'Theme': '主题',
  'Choose one palette for the whole app.': '为整个应用选择一套配色。',
  'Visual mode': '视觉模式',
  'dark': '深色',
  'light': '浅色',
  'Language': '语言',
  'Change interface and formatting language.': '更改界面和格式化语言。',
  'Active language': '当前语言',
  'New expenses': '新支出',
  'Recorded reimbursements': '已记录报销',
  'Reimbursement requests': '报销请求',
  'Open notification center': '打开通知中心',
  'Manual': '指南',
  'You can reopen the quick guide whenever you want.': '你可以随时重新打开快速指南。',
  'Sign out': '退出登录',
  'Delete': '删除',
  'Active chart': '当前图表',
  'Select a view': '选择视图',
  'Where money moves, ShardPay turns it into signal.': '有资金流动的地方，ShardPay 都能把它变成清晰洞察。',
  'Total spend': '总支出',
  'Entries': '条目',
  'Visible people': '可见成员',
  'Not enough data yet.': '数据仍然不足。',
  'There are no groups with spend yet.': '目前还没有有支出的群组。',
  'There are no months with spend yet.': '目前还没有有支出的月份。',
  'There are no people with registered spend yet.': '目前还没有登记支出的成员。',
  'Distribution by category': '按分类分布',
  'Which groups move the most spend': '哪些群组支出最多',
  'Monthly spend': '月度支出',
  'Who is advancing the most': '谁垫付最多',
  'You are in local demo mode because Firebase credentials are missing in --dart-define. The app remains fully navigable.': '由于 --dart-define 中缺少 Firebase 凭据，你当前处于本地演示模式。应用仍可完整浏览。',
  'Share expenses with style: scan receipts, split each item precisely, and join groups by QR or link.': '更高效地分摊支出：扫描小票、精确拆分每个条目，并通过二维码或链接加入群组。',
  'Shared groups': '共享群组',
  'Receipt OCR': '小票 OCR',
  'Exact split': '精确分摊',
  'QR invites': '二维码邀请',
  'Create your account in under a minute': '一分钟内创建账户',
  'Return to your groups and balances': '返回你的群组和余额',
  'Prepare your account to share expenses, receipts and advanced splits from day one.': '准备好你的账户，从第一天起就能共享支出、小票和高级分摊。',
  'Use email or Google to recover groups, invites and pending activity.': '使用邮箱或 Google 恢复群组、邀请和待处理动态。',
  'I already have an account': '我已有账户',
  'I am new here': '我是新用户',
  'How should we call you': '怎么称呼你',
  'Visible name for your group': '你在群组中的显示名',
  'Enter the name you want to show.': '输入你想显示的名字。',
  'Your email': '你的邮箱',
  'Enter your email.': '输入你的邮箱。',
  'Check the email format.': '检查邮箱格式。',
  'Create a password': '创建密码',
  'Your password': '你的密码',
  'At least 6 characters': '至少 6 个字符',
  'Type your password': '输入你的密码',
  'Enter your password.': '输入你的密码。',
  'Use at least 6 characters.': '至少使用 6 个字符。',
  'You will create your account with email. Google can be used later as soon as infrastructure is active.': '你将使用邮箱创建账户。基础设施启用后可再使用 Google。',
  'If you do not have access yet, switch to the new account mode and create it here.': '如果你还没有访问权限，请切换到新账户模式并在这里创建。',
  'Create account and enter': '创建账户并进入',
  'Continue with email': '使用邮箱继续',
  'Continue with Google': '使用 Google 继续',
  'Access is not yet enabled in Google Cloud for this project. Billing/Auth still needs activation.': '此项目在 Google Cloud 中尚未启用访问。仍需激活 Billing/Auth。',
  'Could not reach the server. Check your connection and try again.': '无法连接服务器。请检查网络后重试。',
  'Open manual': '打开指南',
  'Delete profile': '删除资料',
  'Your account will be deleted. Your group participation will remain archived to preserve history.': '你的账户将被删除。你在群组中的参与记录会保留为归档，以保留历史。',
  'Check the items detected on the receipt.': '请检查小票中识别出的条目。',
};

const Map<String, String> _jaTranslations = {
  'Quick manual': 'クイックガイド',
  '1. Create or join groups': '1. グループを作成または参加',
  '2. Add expenses or reimbursements': '2. 支出や返済を追加',
  '3. Review notifications and balances': '3. 通知と残高を確認',
  'Notifications': '通知',
  'There are no notifications with the current filters.': '現在のフィルターでは通知がありません。',
  'You have no pending debts or claims with real accounts across your groups.': 'すべてのグループで実在アカウントに対する未処理の債務や請求はありません。',
  'No pending debts or claims with real accounts across your groups.': 'すべてのグループで実在アカウントに対する未処理の債務や請求はありません。',
  'Owes you money': '相手があなたに支払う',
  'You owe money': 'あなたが相手に支払う',
  'Groups': 'グループ',
  'Global balance': '全体残高',
  'Stats': '統計',
  'Request': '依頼',
  'Reimburse': '返済',
  'Record reimbursement': '返済を記録',
  'Amount': '金額',
  'Cancel': 'キャンセル',
  'Save': '保存',
  'Reimbursement': '返済',
  'Request reimbursement': '返済を依頼',
  'Send': '送信',
  'Add expense': '支出を追加',
  'This group is closed. You can only review it until an admin reopens it.': 'このグループは閉鎖されています。管理者が再開するまで閲覧のみ可能です。',
  'Expense summary': '支出の概要',
  'Main concept': 'メインタイトル',
  'Dinner, fuel, groceries...': '夕食、ガソリン、買い物…',
  'Total amount': '合計金額',
  'Optional note': '任意メモ',
  'Payer and category': '支払った人とカテゴリ',
  'Paid by': '支払った人',
  'pending': '保留中',
  'Category': 'カテゴリ',
  'Who takes part': '参加者',
  'Select the people who share this expense.': 'この支出を分担する人を選択してください。',
  'Pending to link': '連携待ち',
  'Save expense': '支出を保存',
  'Check the concept, amount and selected participants.': 'タイトル、金額、参加者を確認してください。',
  'Group not found.': 'グループが見つかりません。',
  'Group settings': 'グループ設定',
  'Reopen group': 'グループを再開',
  'Close group': 'グループを閉じる',
  'Transfer admin': '管理者を引き継ぐ',
  'Leave group': 'グループを退出',
  'Delete group': 'グループを削除',
  'Overview': '概要',
  'Balance': '残高',
  'Expenses': '支出',
  'Charts': 'グラフ',
  'Expense saved.': '支出を保存しました。',
  'Share link': 'リンクを共有',
  'Group name': 'グループ名',
  'Description': '説明',
  'Add': '追加',
  'Review receipt': 'レシートを確認',
  'Item': '項目',
  'Adjust split': '分担を調整',
  'Save receipt': 'レシートを保存',
  'Edit expense': '支出を編集',
  'Note': 'メモ',
  'Items': '項目',
  'Delete item': '項目を削除',
  'Add item': '項目を追加',
  'Save changes': '変更を保存',
  'Delete expense': '支出を削除',
  'Advanced split': '詳細な分担',
  'Equal split': '均等割り',
  'The percentage sum must be 100%.': '割合の合計は 100% である必要があります。',
  'Close': '閉じる',
  'Reopen': '再開',
  'Group closed.': 'グループを閉じました。',
  'Group reopened.': 'グループを再開しました。',
  'The group is closed. It is available in read-only mode.': 'このグループは閉鎖されており、閲覧専用です。',
  'Group total': 'グループ合計',
  'Your balance': 'あなたの残高',
  'Members': 'メンバー',
  'This group is closed and can only be viewed. The admin can reopen it from the top menu.': 'このグループは閉鎖されており閲覧のみ可能です。管理者は上部メニューから再開できます。',
  'Group dates': 'グループの日付',
  'Created': '作成日',
  'Last update': '最終更新',
  'Closed at': '閉鎖日時',
  'No active closure': '現在閉鎖なし',
  'Quick actions': 'クイックアクション',
  'Invite': '招待',
  'Categories': 'カテゴリ',
  'People and access': 'メンバーとアクセス',
  'Upload receipt': 'レシートをアップロード',
  'Receipt with camera': 'カメラでレシート',
  'Settings': '設定',
  'Group': 'グループ',
  'Search groups': 'グループを検索',
  'Search people': 'メンバーを検索',
  'People': 'メンバー',
  'Join with link or QR': 'リンクまたはQRで参加',
  'You do not have groups yet. Create one or join with an invite.': 'まだグループがありません。新しく作成するか、招待で参加してください。',
  'No groups match your search.': '検索条件に一致するグループはありません。',
  'Closed group': '閉じたグループ',
  'Open group': 'グループを開く',
  'Spent': '支出',
  'Share invite': '招待を共有',
  'Create group': 'グループを作成',
  'Currency': '通貨',
  'Pending people': '参加予定メンバー',
  'Add people even if they do not have an account yet. They can link themselves from the invite later.': 'まだアカウントがなくても追加できます。あとで招待から自分で紐づけできます。',
  'Pending name': '仮の名前',
  'Create': '作成',
  'Group created.': 'グループを作成しました。',
  'Paste group link or code': 'グループリンクまたはコードを貼り付け',
  'Scan QR': 'QRをスキャン',
  'Continue': '続行',
  'No group was found for that invite.': 'その招待に対応するグループは見つかりませんでした。',
  'You can join with your current profile or pick one of the prepared names.': '現在のプロフィールで参加するか、用意された名前を選べます。',
  'Choose one of the names prepared by the admin to link your access.': '管理者が用意した名前から1つ選んでアクセスを紐づけてください。',
  'Prepared by the admin': '管理者が準備した名前',
  'Use this identity': 'この名前を使う',
  'Theme': 'テーマ',
  'Choose one palette for the whole app.': 'アプリ全体の配色を選択します。',
  'Visual mode': '表示モード',
  'dark': 'ダーク',
  'light': 'ライト',
  'Language': '言語',
  'Change interface and formatting language.': '画面表示と言語フォーマットを変更します。',
  'Active language': '現在の言語',
  'New expenses': '新しい支出',
  'Recorded reimbursements': '記録済み返済',
  'Reimbursement requests': '返済リクエスト',
  'Open notification center': '通知センターを開く',
  'Manual': 'ガイド',
  'You can reopen the quick guide whenever you want.': 'クイックガイドはいつでも再度開けます。',
  'Sign out': 'サインアウト',
  'Delete': '削除',
  'Active chart': '表示中のグラフ',
  'Select a view': '表示を選択',
  'Where money moves, ShardPay turns it into signal.': 'お金の動きがある場所を、ShardPay が見える情報に変えます。',
  'Total spend': '総支出',
  'Entries': '件数',
  'Visible people': '表示中の人数',
  'Not enough data yet.': 'まだ十分なデータがありません。',
  'There are no groups with spend yet.': 'まだ支出のあるグループはありません。',
  'There are no months with spend yet.': 'まだ支出のある月はありません。',
  'There are no people with registered spend yet.': 'まだ支出が登録された人はいません。',
  'Distribution by category': 'カテゴリ別分布',
  'Which groups move the most spend': 'どのグループの支出が多いか',
  'Monthly spend': '月別支出',
  'Who is advancing the most': '最も立て替えている人',
  'You are in local demo mode because Firebase credentials are missing in --dart-define. The app remains fully navigable.': '--dart-define に Firebase 認証情報がないため、現在はローカルデモモードです。アプリは引き続き操作できます。',
  'Share expenses with style: scan receipts, split each item precisely, and join groups by QR or link.': 'レシートを読み取り、各項目を正確に分割し、QR やリンクでグループ参加。支出共有をもっとスマートに。',
  'Shared groups': '共有グループ',
  'Receipt OCR': 'レシートOCR',
  'Exact split': '正確な分担',
  'QR invites': 'QR招待',
  'Create your account in under a minute': '1分以内でアカウント作成',
  'Return to your groups and balances': 'グループと残高に戻る',
  'Prepare your account to share expenses, receipts and advanced splits from day one.': '初日から支出、レシート、高度な分担を共有できるようにアカウントを準備します。',
  'Use email or Google to recover groups, invites and pending activity.': 'メールまたは Google で、グループ、招待、未処理の動きを復元します。',
  'I already have an account': 'すでにアカウントがあります',
  'I am new here': 'はじめて使います',
  'How should we call you': '表示名を入力',
  'Visible name for your group': 'グループで表示する名前',
  'Enter the name you want to show.': '表示したい名前を入力してください。',
  'Your email': 'メールアドレス',
  'Enter your email.': 'メールアドレスを入力してください。',
  'Check the email format.': 'メール形式を確認してください。',
  'Create a password': 'パスワードを作成',
  'Your password': 'パスワード',
  'At least 6 characters': '6文字以上',
  'Type your password': 'パスワードを入力',
  'Enter your password.': 'パスワードを入力してください。',
  'Use at least 6 characters.': '6文字以上で入力してください。',
  'You will create your account with email. Google can be used later as soon as infrastructure is active.': 'メールでアカウントを作成します。インフラが有効になれば後から Google も使えます。',
  'If you do not have access yet, switch to the new account mode and create it here.': 'まだアクセスがない場合は、新規アカウントモードに切り替えてここで作成してください。',
  'Create account and enter': 'アカウントを作成して開始',
  'Continue with email': 'メールで続行',
  'Continue with Google': 'Googleで続行',
  'Access is not yet enabled in Google Cloud for this project. Billing/Auth still needs activation.': 'このプロジェクトでは Google Cloud のアクセスがまだ有効ではありません。Billing/Auth の有効化が必要です。',
  'Could not reach the server. Check your connection and try again.': 'サーバーに接続できませんでした。接続を確認して再試行してください。',
  'Open manual': 'ガイドを開く',
  'Delete profile': 'プロフィールを削除',
  'Your account will be deleted. Your group participation will remain archived to preserve history.': 'アカウントは削除されます。履歴を保持するため、グループ参加情報はアーカイブされたまま残ります。',
  'Check the items detected on the receipt.': 'レシートから検出された項目を確認してください。',
};
